name = "minekeep-help-bot"
compatibility_date = "2023-05-18"
main = "./src/index.js"
# update package.json if updating main to typescript

vars = { DEV = false }

# Development vars automatically set on localdev
[env.dev]
vars = { DEV = true }