name = "minekeep-help-bot"
compatibility_date = "2023-05-18"
main = "./src/index.js"
# update package.json if updating main=

# [secrets]
# DISCORD_TOKEN = 
# DISCORD_PUBLIC_KEY = 
# DISCORD_APPLICATION_ID = 