import { AutoRouter } from 'itty-router';
import { InteractionResponseType, InteractionType, verifyKey } from 'discord-interactions';
import { regscript } from './regscript.js';
import { articleItems, articles } from './articles.js';

/*
 -- TODO LIST
  - ping option for notifying users
  - switch away from using commands and use user applications instead
    note: use option 3: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types
  - use built-in router instead of using itty-router
  - convert to Typescript for better type safety (optional)
*/

class JsonResponse extends Response {
	constructor(body, init) {
		const jsonBody = JSON.stringify(body);
		init = init || {
			headers: {
				'content-type': 'application/json;charset=UTF-8'
			}
		};
		super(jsonBody, init);
	}
}

const router = AutoRouter();

/*
 * Only register the commandreg script if
 * on localdev, otherwise it may be abused
 * DO NOT REMOVE UNUSED REQUEST VARIABLE
 */
router.get('/', async (request, vars) => {
	return vars.DEV
		? new Response(await regscript(vars))
		: new Response(
				'👋 Minekeep Discord help bot endpoint\nGive feedback and suggestions regarding this bot to a Minekeep staff member so we can improve!'
			);
});

/*
 * Routing for all Discord requests following this JSON payload:
 * https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object
 */
router.post('/', async (request, vars) => {
	const { isValid, interaction } = await server.verifyDiscordRequest(request, vars);
	if (!isValid || !interaction) return new Response('Bad request signature', 401);

	// Ping required during the initial webhook handshake
	// to configure the webhook in the developer portal
	if (interaction.type === InteractionType.PING) {
		return new JsonResponse({
			type: InteractionResponseType.PONG
		});
	}

	// Handle command and reply with the proper article
	else if (interaction.type === InteractionType.APPLICATION_COMMAND) {
		const article = articleItems.indexOf(interaction.data.options[0].value);

		if (article == -1) return new Response('Bad request - article not found', 404);

		return new JsonResponse({
			type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
			data: {
				//content: "<@USER ID GOES HERE TODO>"
				embeds: [{ 
					description: articles[article],
					footer: {
						text: "This response was auto-generated by the Minekeep help bot. Send feedback to Minekeep staff.",
						//icon_url: ""
					}
				}]
			}
		});
	};
});
router.all('*', () => new Response('Endpoint not found', 404));

/*
 * Verify request to make sure Discord is the proper sender
 * to prevent attacks and possible exceptions
 */
async function verifyDiscordRequest(request, vars) {
	const signature = request.headers.get('x-signature-ed25519');
	const timestamp = request.headers.get('x-signature-timestamp');
	const body = await request.text();
	const isValidRequest =
		signature &&
		timestamp &&
		(await verifyKey(body, signature, timestamp, vars.DISCORD_PUBLIC_KEY));
	if (!isValidRequest) return { isValid: false };
	return { isValid: true, interaction: JSON.parse(body) };
}

// Create request router and verifier
const server = {
	verifyDiscordRequest,
	fetch: router.fetch
};
export default server;
